import type { ProjectConfig } from './config.js';

// ─── Circom circuits ───────────────────────────────────────────────────────────

export function generateTransferCircuit(cfg: ProjectConfig): string {
  const { N, C } = cfg;

  // Build per-element equality constraints
  const decConstraints = Array.from(
    { length: N },
    (_, i) => `    dec.decrypted[${i}] === oldMessage[${i}];`
  ).join('\n');

  const encConstraints = Array.from(
    { length: C },
    (_, i) => `    enc.ciphertext[${i}] === newComputedCipherText[${i}];`
  ).join('\n');

  return `// Generated by Geheimnis — edit by hand only if you know what you are doing
pragma circom 2.1.5;

include "babyjub.circom";
include "ecdh.circom";
include "poseidon-cipher.circom";

/*
 * EcdhPoseidonTransfer
 *
 * Proves that the prover:
 *  1. Owns the private key corresponding to myPublicKey (BabyPbk check)
 *  2. Correctly decrypted oldComputedCipherText using ECDH(myPrivKey, oldSenderPublicKey)
 *  3. Re-encrypted the same plaintext for the recipient using ECDH(myPrivKey, newReciverPublicKey)
 *
 * N = ${N}  (plaintext field elements)
 * C = ${C}  (ciphertext field elements = ceil(N/3)*3 + 1)
 *
 * Public signal layout (_pubSignals indices):
 *   [0..1]            newReciverPublicKey[2]
 *   [2]               newNonce  (used as on-chain timestamp)
 *   [3..${2 + C}]     newComputedCipherText[${C}]
 *   [${3 + C}..${2 + 2 * C}]  oldComputedCipherText[${C}]
 *   [${3 + 2 * C}..${4 + 2 * C}]  myPublicKey[2]
 */
template EcdhPoseidonTransfer() {
    // ── public inputs ──
    signal input newReciverPublicKey[2];
    signal input newNonce;
    signal input newComputedCipherText[${C}];
    signal input oldComputedCipherText[${C}];
    signal input myPublicKey[2];

    // ── private inputs ──
    signal input myPrivateKey;
    signal input oldSenderPublicKey[2];
    signal input newResultKey[2];
    signal input oldResultKey[2];
    signal input newMessage[${N}];
    signal input oldMessage[${N}];
    signal input oldNonce;

    // 1. Key derivation — prove ownership of myPrivateKey
    component pubKeyFromPriv = BabyPbk();
    pubKeyFromPriv.in <== myPrivateKey;
    myPublicKey[0] === pubKeyFromPriv.Ax;
    myPublicKey[1] === pubKeyFromPriv.Ay;

    // 2. Decrypt old ciphertext
    component ecdhOld = Ecdh();
    ecdhOld.privateKey <== myPrivateKey;
    ecdhOld.publicKey[0] <== oldSenderPublicKey[0];
    ecdhOld.publicKey[1] <== oldSenderPublicKey[1];
    oldResultKey[0] === ecdhOld.sharedKey[0];
    oldResultKey[1] === ecdhOld.sharedKey[1];

    component dec = PoseidonDecrypt(${N});
    dec.ciphertext <== oldComputedCipherText;
    dec.nonce <== oldNonce;
    dec.key[0] <== oldResultKey[0];
    dec.key[1] <== oldResultKey[1];
${decConstraints}

    // 3. Encrypt new ciphertext for recipient
    component ecdhNew = Ecdh();
    ecdhNew.privateKey <== myPrivateKey;
    ecdhNew.publicKey[0] <== newReciverPublicKey[0];
    ecdhNew.publicKey[1] <== newReciverPublicKey[1];
    newResultKey[0] === ecdhNew.sharedKey[0];
    newResultKey[1] === ecdhNew.sharedKey[1];

    component enc = PoseidonEncrypt(${N});
    enc.message <== newMessage;
    enc.nonce <== newNonce;
    enc.key[0] <== newResultKey[0];
    enc.key[1] <== newResultKey[1];
${encConstraints}
}

component main {
    public[
        newReciverPublicKey,
        newNonce,
        newComputedCipherText,
        oldComputedCipherText,
        myPublicKey
    ]
} = EcdhPoseidonTransfer();
`;
}

export function generateAddDataCircuit(cfg: ProjectConfig): string {
  const { N, C } = cfg;

  const decConstraints = Array.from(
    { length: N },
    (_, i) => `    dec.decrypted[${i}] === oldMessage[${i}];`
  ).join('\n');

  const encConstraints = Array.from(
    { length: C },
    (_, i) => `    enc.ciphertext[${i}] === newComputedCipherText[${i}];`
  ).join('\n');

  // Mutation guard: when enableOneValueCheck == 1, enforce newMessage === oldMessage
  // Uses quadratic constraint: enableOneValueCheck * (newMessage[i] - oldMessage[i]) === 0
  const mutationGuard = Array.from(
    { length: N },
    (_, i) => `    enableOneValueCheck * (newMessage[${i}] - oldMessage[${i}]) === 0;`
  ).join('\n');

  return `// Generated by Geheimnis — edit by hand only if you know what you are doing
pragma circom 2.1.5;

include "babyjub.circom";
include "ecdh.circom";
include "poseidon-cipher.circom";

/*
 * AddNewDataEncrypt
 *
 * Used for minting (enableOneValueCheck = 0) and reCipher (enableOneValueCheck = 1).
 *
 * Proves that the prover:
 *  1. Owns the private key corresponding to myPublicKey (BabyPbk check)
 *  2. Correctly decrypted oldComputedCipherText
 *  3. Correctly encrypted newMessage into newComputedCipherText
 *  4. When enableOneValueCheck = 1: newMessage === oldMessage (re-encrypt only, no changes)
 *
 * N = ${N}  (plaintext field elements)
 * C = ${C}  (ciphertext field elements = ceil(N/3)*3 + 1)
 *
 * Public signal layout (_pubSignals indices):
 *   [0..1]            newReciverPublicKey[2]
 *   [2]               newNonce  (used as on-chain timestamp)
 *   [3..${2 + C}]     newComputedCipherText[${C}]
 *   [${3 + C}..${2 + 2 * C}]  oldComputedCipherText[${C}]
 *   [${3 + 2 * C}..${4 + 2 * C}]  myPublicKey[2]
 *   [${5 + 2 * C}]   enableOneValueCheck  (0 = mint, 1 = reCipher)
 */
template AddNewDataEncrypt() {
    // ── public inputs ──
    signal input newReciverPublicKey[2];
    signal input newNonce;
    signal input newComputedCipherText[${C}];
    signal input oldComputedCipherText[${C}];
    signal input myPublicKey[2];
    signal input enableOneValueCheck;

    // ── private inputs ──
    signal input myPrivateKey;
    signal input oldSenderPublicKey[2];
    signal input newResultKey[2];
    signal input oldResultKey[2];
    signal input newMessage[${N}];
    signal input oldMessage[${N}];
    signal input oldNonce;

    // Validate enableOneValueCheck is binary
    enableOneValueCheck * (1 - enableOneValueCheck) === 0;

    // 1. Key derivation — prove ownership of myPrivateKey
    component pubKeyFromPriv = BabyPbk();
    pubKeyFromPriv.in <== myPrivateKey;
    myPublicKey[0] === pubKeyFromPriv.Ax;
    myPublicKey[1] === pubKeyFromPriv.Ay;

    // 2. Decrypt old ciphertext
    component ecdhOld = Ecdh();
    ecdhOld.privateKey <== myPrivateKey;
    ecdhOld.publicKey[0] <== oldSenderPublicKey[0];
    ecdhOld.publicKey[1] <== oldSenderPublicKey[1];
    oldResultKey[0] === ecdhOld.sharedKey[0];
    oldResultKey[1] === ecdhOld.sharedKey[1];

    component dec = PoseidonDecrypt(${N});
    dec.ciphertext <== oldComputedCipherText;
    dec.nonce <== oldNonce;
    dec.key[0] <== oldResultKey[0];
    dec.key[1] <== oldResultKey[1];
${decConstraints}

    // 3. Encrypt new ciphertext for recipient (self for mint/reCipher)
    component ecdhNew = Ecdh();
    ecdhNew.privateKey <== myPrivateKey;
    ecdhNew.publicKey[0] <== newReciverPublicKey[0];
    ecdhNew.publicKey[1] <== newReciverPublicKey[1];
    newResultKey[0] === ecdhNew.sharedKey[0];
    newResultKey[1] === ecdhNew.sharedKey[1];

    component enc = PoseidonEncrypt(${N});
    enc.message <== newMessage;
    enc.nonce <== newNonce;
    enc.key[0] <== newResultKey[0];
    enc.key[1] <== newResultKey[1];
${encConstraints}

    // 4. Mutation guard — when reCipher mode, enforce no plaintext changes
${mutationGuard}
}

component main {
    public[
        newReciverPublicKey,
        newNonce,
        newComputedCipherText,
        oldComputedCipherText,
        myPublicKey,
        enableOneValueCheck
    ]
} = AddNewDataEncrypt();
`;
}

// ─── Solidity contract ────────────────────────────────────────────────────────

export function generateContract(cfg: ProjectConfig): string {
  const { N, C, S_t, S_a, hasMintLogic } = cfg;

  const noteFields = Array.from({ length: C }, (_, i) => `        uint256 field${i + 1};`).join('\n');
  const setNoteParams = Array.from({ length: C }, (_, i) => `uint256 f${i + 1}`).join(', ');
  const setNoteBody = Array.from({ length: C }, (_, i) => `            field${i + 1}: f${i + 1}`).join(',\n');
  const ctPopulate = Array.from({ length: C }, (_, i) => `        ct[${i}] = tokenIdToNote[tokenId].field${i + 1};`).join('\n');
  const setNoteArgs = Array.from({ length: C }, (_, i) => `_pubSignals[${3 + i}]`).join(', ');

  // Old ciphertext checks — used in both reCipher and verifiedTransferFrom
  const oldCipherChecksFor = (idVar: string) =>
    Array.from({ length: C }, (_, i) =>
      `        require(\n            tokenIdToNote[${idVar}].field${i + 1} == _pubSignals[${3 + C + i}],\n            "OLD CIPHERTEXT MISMATCH"\n        );`
    ).join('\n');

  // ── Storage: mint-logic-specific fields ───────────────────────────────────
  const mintStorage = hasMintLogic ? `
    uint256 public immutable maxSupply;
    uint256 public immutable mintPrice;
    uint256 public tokenIds;
    address public minter;
` : `
    uint256 public tokenIds;
`;

  // ── Constructor ───────────────────────────────────────────────────────────
  const constructor_ = hasMintLogic ? `
    constructor(
        address _transferVerifier,
        address _addDataVerifier,
        uint256 _maxSupply,
        uint256 _mintPrice
    ) {
        _initializeOwner(msg.sender);
        transferVerifier = TransferVerifier(_transferVerifier);
        addDataVerifier  = AddDataVerifier(_addDataVerifier);
        maxSupply  = _maxSupply;
        mintPrice  = _mintPrice;
        verifierVersion = 1;
    }
` : `
    constructor(address _transferVerifier, address _addDataVerifier) {
        _initializeOwner(msg.sender);
        transferVerifier = TransferVerifier(_transferVerifier);
        addDataVerifier  = AddDataVerifier(_addDataVerifier);
        verifierVersion = 1;
    }
`;

  // ── Owner functions ───────────────────────────────────────────────────────
  const minterSetter = hasMintLogic ? `
    function setMinter(address _minter) external onlyOwner {
        minter = _minter;
    }
` : '';

  // ── Mint section ──────────────────────────────────────────────────────────
  const mintSection = hasMintLogic ? `
    // ─── Public mint ───────────────────────────────────────────────────────────

    function mint(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[${S_a}] calldata _pubSignals,
        address to
    ) external payable {
        require(msg.value == mintPrice, "Wrong mint price");
        require(_pubSignals[${S_a - 1}] == 0, "Must be mint mode");
        _doMint(_pA, _pB, _pC, _pubSignals, to);
        (bool ok,) = owner().call{value: msg.value}("");
        require(ok, "ETH transfer failed");
    }

    /// @notice Mint via trusted minter contract (no ETH check here).
    /// @dev Deploy a CipherMinter contract and set it via setMinter().
    function mintFrom(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[${S_a}] calldata _pubSignals,
        address to
    ) external {
        require(msg.sender == minter, "Only minter");
        require(_pubSignals[${S_a - 1}] == 0, "Must be mint mode");
        _doMint(_pA, _pB, _pC, _pubSignals, to);
    }

    function _doMint(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[${S_a}] calldata _pubSignals,
        address to
    ) internal {
        tokenIds++;
        require(tokenIds <= maxSupply, "Max supply reached");
        require(addDataVerifier.verifyProof(_pA, _pB, _pC, _pubSignals), "Invalid proof");
        _setNote(${setNoteArgs}, tokenIds);
        _mint(to, tokenIds);
        _setTimestampAndFlag(tokenIds, _pubSignals[2], true);
    }
` : `
    // ─── Admin mint ────────────────────────────────────────────────────────────
    // No public minting — owner controls all token creation.
    // Extend this with your own pricing / allowlist logic as needed.

    function adminMint(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[${S_a}] calldata _pubSignals,
        address to
    ) external onlyOwner {
        require(_pubSignals[${S_a - 1}] == 0, "Must be mint mode");
        tokenIds++;
        require(addDataVerifier.verifyProof(_pA, _pB, _pC, _pubSignals), "Invalid proof");
        _setNote(${setNoteArgs}, tokenIds);
        _mint(to, tokenIds);
        _setTimestampAndFlag(tokenIds, _pubSignals[2], true);
    }
`;

  return `// SPDX-License-Identifier: UNLICENSED
// Generated by Geheimnis — edit by hand only if you know what you are doing
pragma solidity ^0.8.13;

import {Groth16Verifier as TransferVerifier} from "./Groth16Verifier_Transfer.sol";
import {Groth16Verifier as AddDataVerifier} from "./Groth16Verifier_AddData.sol";
import {ERC721} from "solady/src/tokens/ERC721.sol";
import {Ownable} from "solady/src/auth/Ownable.sol";
import {BabyJubjub} from "./BabyJubjub.sol";

/// @notice ERC-721 with ZK-verified encrypted on-chain metadata.
/// @dev N=${N} plaintext slots, C=${C} ciphertext fields per token.
///      Standard transferFrom is disabled — use verifiedTransferFrom.
contract EncryptedERC721 is ERC721, Ownable {

    event VerifiedTransfer(
        uint256[2] indexed from,
        uint256[2] indexed to,
        uint256 indexed id
    );
    event VerifiersUpdated(address transferVerifier, address addDataVerifier, uint256 version);

    TransferVerifier private transferVerifier;
    AddDataVerifier  private addDataVerifier;

    mapping(address => uint256[2]) public userPublicKeys;
    mapping(uint256 => Note) public tokenIdToNote;

    uint256 public constant N = ${N};
    uint256 public constant C = ${C};
    uint256 public verifierVersion;
${mintStorage}
    struct Note {
${noteFields}
    }
${constructor_}
    function name()   public pure override returns (string memory) { return "${cfg.name}"; }
    function symbol() public pure override returns (string memory) { return "${cfg.symbol}"; }
    function tokenURI(uint256) public pure override returns (string memory) { return ""; }

    // ─── Timestamp & flag packing ──────────────────────────────────────────────
    // extraData (96 bits): bits 0-94 = timestamp, bit 95 = flag
    // flag=true  → self-encrypted (mint or reCipher)
    // flag=false → ECDH-encrypted by previous sender

    function _setTimestampAndFlag(uint256 tokenId, uint256 ts, bool flag) internal {
        require(ts < (1 << 95), "Timestamp overflow");
        uint96 packed = uint96(ts);
        if (flag) packed |= uint96(1 << 95);
        _setExtraData(tokenId, packed);
    }

    // ─── Public key registration ───────────────────────────────────────────────

    function registerPublicKey(uint256 x, uint256 y) external {
        require(BabyJubjub.isValidPublicKey(x, y), "Invalid Baby Jubjub point");
        userPublicKeys[msg.sender] = [x, y];
    }

    // ─── Owner functions ───────────────────────────────────────────────────────
${minterSetter}
    function updateVerifiers(address _transfer, address _addData) external onlyOwner {
        transferVerifier = TransferVerifier(_transfer);
        addDataVerifier  = AddDataVerifier(_addData);
        verifierVersion++;
        emit VerifiersUpdated(_transfer, _addData, verifierVersion);
    }
${mintSection}
    // ─── Re-cipher ─────────────────────────────────────────────────────────────

    function reCipher(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[${S_a}] calldata _pubSignals,
        uint256 id
    ) external {
        require(ownerOf(id) == msg.sender, "Not token owner");
        require(_pubSignals[${S_a - 1}] == 1, "Must be reCipher mode");
        require(!_getFlag(id), "Already self-encrypted; transfer first");

${oldCipherChecksFor('id')}

        require(addDataVerifier.verifyProof(_pA, _pB, _pC, _pubSignals), "Invalid proof");
        _setNote(${setNoteArgs}, id);
        _setTimestampAndFlag(id, _pubSignals[2], true);
    }

    // ─── Verified transfer ─────────────────────────────────────────────────────

    function transferFrom(address, address, uint256) public payable override {
        revert("Use verifiedTransferFrom");
    }
    function safeTransferFrom(address, address, uint256) public payable override {
        revert("Use verifiedTransferFrom");
    }
    function safeTransferFrom(address, address, uint256, bytes calldata) public payable override {
        revert("Use verifiedTransferFrom");
    }

    function verifiedTransferFrom(
        address from,
        address to,
        uint256 id,
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[${S_t}] calldata _pubSignals
    ) external {
        require(userPublicKeys[to][0] == _pubSignals[0], "Recipient key X mismatch");
        require(userPublicKeys[to][1] == _pubSignals[1], "Recipient key Y mismatch");

${oldCipherChecksFor('id')}

        require(transferVerifier.verifyProof(_pA, _pB, _pC, _pubSignals), "Invalid proof");

        _setNote(${setNoteArgs}, id);
        _setTimestampAndFlag(id, _pubSignals[2], false);
        ERC721.transferFrom(from, to, id);

        emit VerifiedTransfer(
            [_pubSignals[${3 + 2 * C}], _pubSignals[${4 + 2 * C}]],
            [_pubSignals[0], _pubSignals[1]],
            id
        );
    }

    // ─── View functions ────────────────────────────────────────────────────────

    function plaintextLength()  external pure returns (uint256) { return N; }
    function ciphertextLength() external pure returns (uint256) { return C; }

    function getEncryptedNote(uint256 tokenId)
        external view
        returns (uint256[] memory ciphertext, uint256 timestamp, bool flag)
    {
        uint256[] memory ct = new uint256[](${C});
${ctPopulate}
        (timestamp, flag) = getTimestampAndFlag(tokenId);
        return (ct, timestamp, flag);
    }

    function getTimestampAndFlag(uint256 tokenId)
        public view
        returns (uint256 timestamp, bool flag)
    {
        uint96 packed = _getExtraData(tokenId);
        timestamp = uint256(packed & ~uint96(1 << 95));
        flag = (packed & uint96(1 << 95)) != 0;
    }

    function _getFlag(uint256 tokenId) internal view returns (bool) {
        return (_getExtraData(tokenId) & uint96(1 << 95)) != 0;
    }

    // ─── Internal ──────────────────────────────────────────────────────────────

    function _setNote(${setNoteParams}, uint256 tokenId) internal {
        tokenIdToNote[tokenId] = Note({
${setNoteBody}
        });
    }
}
`;
}

// ─── BabyJubjub helper (unchanged from reference impl) ───────────────────────

export function generateBabyJubjub(): string {
  return `// SPDX-License-Identifier: MIT
// Minimal Baby Jubjub curve point validation for public key registration.
pragma solidity ^0.8.13;

library BabyJubjub {
    // Baby Jubjub curve parameters (twisted Edwards form: a*x^2 + y^2 = 1 + d*x^2*y^2)
    uint256 constant Q  = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 constant A  = 168700;
    uint256 constant D  = 168696;

    function isValidPublicKey(uint256 x, uint256 y) internal pure returns (bool) {
        if (x >= Q || y >= Q) return false;
        // Check curve equation: A*x^2 + y^2 ≡ 1 + D*x^2*y^2 (mod Q)
        uint256 x2 = mulmod(x, x, Q);
        uint256 y2 = mulmod(y, y, Q);
        uint256 lhs = addmod(mulmod(A, x2, Q), y2, Q);
        uint256 rhs = addmod(1, mulmod(mulmod(D, x2, Q), y2, Q), Q);
        return lhs == rhs;
    }
}
`;
}

// ─── Deploy script ────────────────────────────────────────────────────────────

export function generateDeployScript(cfg: ProjectConfig): string {
  const constructorArgs = cfg.hasMintLogic
    ? `address(transferVerifier),
            address(addDataVerifier),
            ${cfg.maxSupply},
            ${Math.round(parseFloat(cfg.mintPrice!) * 1e18)} // ${cfg.mintPrice} ETH`
    : `address(transferVerifier),
            address(addDataVerifier)`;

  return `// SPDX-License-Identifier: UNLICENSED
// Generated by Geheimnis
pragma solidity ^0.8.13;

import {Script} from "forge-std/Script.sol";
import {EncryptedERC721} from "../src/EncryptedERC721.sol";
import {Groth16Verifier as TransferVerifier} from "../src/Groth16Verifier_Transfer.sol";
import {Groth16Verifier as AddDataVerifier} from "../src/Groth16Verifier_AddData.sol";

contract Deploy is Script {
    function run() external {
        vm.startBroadcast();

        TransferVerifier transferVerifier = new TransferVerifier();
        AddDataVerifier  addDataVerifier  = new AddDataVerifier();

        new EncryptedERC721(
            ${constructorArgs}
        );

        vm.stopBroadcast();
    }
}
`;
}

// ─── TypeScript SDK bindings ──────────────────────────────────────────────────

export function generateBindings(cfg: ProjectConfig): string {
  const { N, C } = cfg;

  return `// Generated by Geheimnis — edit by hand only if you know what you are doing
// SDK bindings for ${cfg.name} (N=${N}, C=${C})
import { buildBabyjub, buildPoseidon } from 'circomlibjs';
import { deriveSecretScalar } from '@zk-kit/eddsa-poseidon';
import { groth16 } from 'snarkjs';

export type FieldElement = bigint;
export type PublicKey = [FieldElement, FieldElement];

// ─── Poseidon cipher helpers ──────────────────────────────────────────────────

let _poseidon: Awaited<ReturnType<typeof buildPoseidon>> | null = null;
let _babyJub: Awaited<ReturnType<typeof buildBabyjub>> | null = null;

async function poseidon() {
  if (!_poseidon) _poseidon = await buildPoseidon();
  return _poseidon;
}
async function babyJub() {
  if (!_babyJub) _babyJub = await buildBabyjub();
  return _babyJub;
}

/**
 * Encrypt N field elements using Poseidon sponge.
 * Returns C = ${C} ciphertext field elements.
 */
export async function poseidonEncrypt(
  message: FieldElement[/* ${N} */],
  key: PublicKey,
  nonce: FieldElement
): Promise<FieldElement[]> {
  const p = await poseidon();
  const F = p.F;

  let state = [F.zero, F.e(key[0]), F.e(key[1]), F.e(nonce + (BigInt(${N}) << 128n))];
  const ciphertext: FieldElement[] = [];

  // Pad message to multiple of 3
  const padded = [...message];
  while (padded.length % 3 !== 0) padded.push(0n);

  for (let i = 0; i < padded.length; i += 3) {
    state = p([state[0], state[1], state[2], state[3]]);
    for (let j = 0; j < 3; j++) {
      const ct = F.add(state[j], F.e(padded[i + j]));
      ciphertext.push(F.toObject(ct));
      state[j] = ct;
    }
  }

  // Authentication tag
  state = p([state[0], state[1], state[2], state[3]]);
  ciphertext.push(F.toObject(state[0]));

  return ciphertext; // length = ${C}
}

/**
 * Decrypt C = ${C} ciphertext field elements back to N = ${N} plaintext elements.
 */
export async function poseidonDecrypt(
  ciphertext: FieldElement[/* ${C} */],
  key: PublicKey,
  nonce: FieldElement
): Promise<FieldElement[]> {
  const p = await poseidon();
  const F = p.F;

  let state = [F.zero, F.e(key[0]), F.e(key[1]), F.e(nonce + (BigInt(${N}) << 128n))];
  const decrypted: FieldElement[] = [];
  const padded = ${Math.ceil(N / 3) * 3};

  for (let i = 0; i < padded; i += 3) {
    state = p([state[0], state[1], state[2], state[3]]);
    for (let j = 0; j < 3; j++) {
      const pt = F.sub(F.e(ciphertext[i + j]), state[j]);
      decrypted.push(F.toObject(pt));
      state[j] = F.e(ciphertext[i + j]);
    }
  }

  // Verify authentication tag
  state = p([state[0], state[1], state[2], state[3]]);
  if (F.toObject(state[0]) !== ciphertext[${C - 1}]) {
    throw new Error('Poseidon decryption: authentication tag mismatch');
  }

  return decrypted.slice(0, ${N});
}

// ─── ECDH ─────────────────────────────────────────────────────────────────────

/**
 * Derive Baby Jubjub public key from a raw private key.
 * The private key must be passed through deriveSecretScalar first.
 */
export async function derivePublicKey(rawPrivateKey: Uint8Array | string): Promise<PublicKey> {
  const bjj = await babyJub();
  const scalar = deriveSecretScalar(rawPrivateKey);
  const point = bjj.mulPointEscalar(bjj.Base8, scalar);
  return [bjj.F.toObject(point[0]), bjj.F.toObject(point[1])];
}

/**
 * Compute ECDH shared key: scalar * theirPublicKey
 */
export async function computeSharedKey(
  rawPrivateKey: Uint8Array | string,
  theirPublicKey: PublicKey
): Promise<PublicKey> {
  const bjj = await babyJub();
  const scalar = deriveSecretScalar(rawPrivateKey);
  const point = bjj.mulPointEscalar(
    [bjj.F.e(theirPublicKey[0]), bjj.F.e(theirPublicKey[1])],
    scalar
  );
  return [bjj.F.toObject(point[0]), bjj.F.toObject(point[1])];
}

// ─── Proof input builders ─────────────────────────────────────────────────────

export interface MintInput {
  // private
  myPrivateKey: string;
  oldSenderPublicKey: [string, string];
  newResultKey: [string, string];
  oldResultKey: [string, string];
  newMessage: string[];
  oldMessage: string[];
  oldNonce: string;
  // public
  newReciverPublicKey: [string, string];
  newNonce: string;
  newComputedCipherText: string[];
  oldComputedCipherText: string[];
  myPublicKey: [string, string];
  enableOneValueCheck: string;
}

/**
 * Build all inputs for the AddData circuit (mint mode).
 * Pass the result directly to snarkjs.groth16.fullProve().
 */
export async function buildMintInput(
  rawPrivateKey: Uint8Array | string,
  message: FieldElement[/* ${N} */],
  nonce: FieldElement
): Promise<MintInput> {
  const myPubKey = await derivePublicKey(rawPrivateKey);
  const bjj = await babyJub();
  const scalar = deriveSecretScalar(rawPrivateKey);

  // Self-encrypt: ECDH with own public key
  const sharedKey = await computeSharedKey(rawPrivateKey, myPubKey);
  const ciphertext = await poseidonEncrypt(message, sharedKey, nonce);

  // For mint, "old" ciphertext is a dummy (same as new — the circuit skips the check when mode=0)
  const zeroKey: PublicKey = [0n, 1n]; // additive identity on Baby Jubjub y-axis
  const zeroCipher = await poseidonEncrypt(message, sharedKey, nonce);

  return {
    myPrivateKey: scalar.toString(),
    oldSenderPublicKey: [myPubKey[0].toString(), myPubKey[1].toString()],
    newResultKey: [sharedKey[0].toString(), sharedKey[1].toString()],
    oldResultKey: [sharedKey[0].toString(), sharedKey[1].toString()],
    newMessage: message.map(String),
    oldMessage: message.map(String),
    oldNonce: nonce.toString(),
    newReciverPublicKey: [myPubKey[0].toString(), myPubKey[1].toString()],
    newNonce: nonce.toString(),
    newComputedCipherText: ciphertext.map(String),
    oldComputedCipherText: zeroCipher.map(String),
    myPublicKey: [myPubKey[0].toString(), myPubKey[1].toString()],
    enableOneValueCheck: '0',
  };
}

export interface TransferInput {
  // private
  myPrivateKey: string;
  oldSenderPublicKey: [string, string];
  newResultKey: [string, string];
  oldResultKey: [string, string];
  newMessage: string[];
  oldMessage: string[];
  oldNonce: string;
  // public
  newReciverPublicKey: [string, string];
  newNonce: string;
  newComputedCipherText: string[];
  oldComputedCipherText: string[];
  myPublicKey: [string, string];
}

/**
 * Build all inputs for the transfer circuit.
 * The caller must first decrypt the old ciphertext to get oldMessage + oldNonce.
 */
export async function buildTransferInput(
  rawPrivateKey: Uint8Array | string,
  oldMessage: FieldElement[/* ${N} */],
  oldCiphertext: FieldElement[/* ${C} */],
  oldNonce: FieldElement,
  oldSenderPubKey: PublicKey,
  recipientPubKey: PublicKey,
  newNonce: FieldElement
): Promise<TransferInput> {
  const myPubKey = await derivePublicKey(rawPrivateKey);
  const scalar = deriveSecretScalar(rawPrivateKey);

  const oldSharedKey = await computeSharedKey(rawPrivateKey, oldSenderPubKey);
  const newSharedKey = await computeSharedKey(rawPrivateKey, recipientPubKey);

  const newCiphertext = await poseidonEncrypt(oldMessage, newSharedKey, newNonce);

  return {
    myPrivateKey: scalar.toString(),
    oldSenderPublicKey: [oldSenderPubKey[0].toString(), oldSenderPubKey[1].toString()],
    newResultKey: [newSharedKey[0].toString(), newSharedKey[1].toString()],
    oldResultKey: [oldSharedKey[0].toString(), oldSharedKey[1].toString()],
    newMessage: oldMessage.map(String),
    oldMessage: oldMessage.map(String),
    oldNonce: oldNonce.toString(),
    newReciverPublicKey: [recipientPubKey[0].toString(), recipientPubKey[1].toString()],
    newNonce: newNonce.toString(),
    newComputedCipherText: newCiphertext.map(String),
    oldComputedCipherText: oldCiphertext.map(String),
    myPublicKey: [myPubKey[0].toString(), myPubKey[1].toString()],
  };
}

// ─── Groth16 proof helpers ────────────────────────────────────────────────────

export async function proveTransfer(
  input: TransferInput,
  wasmPath: string,
  zkeyPath: string
) {
  return groth16.fullProve(input, wasmPath, zkeyPath);
}

export async function proveMint(
  input: MintInput,
  wasmPath: string,
  zkeyPath: string
) {
  return groth16.fullProve(input, wasmPath, zkeyPath);
}
`;
}

// ─── Output package.json ──────────────────────────────────────────────────────

export function generateOutputPackageJson(cfg: ProjectConfig): string {
  return JSON.stringify(
    {
      name: cfg.name.toLowerCase().replace(/\s+/g, '-'),
      version: '0.1.0',
      type: 'module',
      dependencies: {
        circomlibjs: '^0.1.7',
        snarkjs: '^0.7.4',
        '@zk-kit/eddsa-poseidon': '^1.0.2',
      },
    },
    null,
    2
  );
}

// ─── Foundry config ───────────────────────────────────────────────────────────

export function generateFoundryToml(cfg: ProjectConfig): string {
  return `[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "solady/=lib/solady/",
    "forge-std/=lib/forge-std/src/"
]
`;
}
